name: "Hello World"
descrption: "Greet some and record the time"
input:
  who-to-greet:
    description: "Who to greet"
    required: false
    default: "World"
outputs:
  time:
    description: "The time we greeted you"
runs:
  using: "node12"
  main: "dist/index.js"
