on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: intall dependency
        run: npm install
      - name: Hello
        uses: ./
        id: hello
        #with:
        # who-to-greet: "Lazcat"
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
